# -*- coding: utf-8 -*-
"""Assignment02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/[REDACTED]

1. This Colab is designed for the course "[REDACTED]" instructed by [REDACTED].

2. First, copy this Colab notebook to your Drive. Then, read the instruction of this assignment. 

3. Rename copied notebbok to **[REDACTED]**. For example, **[REDACTED]**

4. When you complete your assignment, you need to:

  a. First, download your Colab notebook as a IPYNB file

  b. Next, upload downloaded Colab notebook to the specific drive folder [REDACTED] before **[REDACTED]**

  c. Then, please submit the link of your **uploaded** file to [REDACTED]. 
  
  The link of **uploaded** IPYNB file can be found by clicking **Share>Get Link** on the top right.
  
Note that you can re-submit your assigment by replacing the old one.

## Personal Information
Please fill in your details below.

Name: [REDACTED]

Student ID: [REDACTED]

Department/Program: [REDACTED]
"""

# Load packages
import matplotlib.pyplot as plt
import numpy as np

# Used for interact
from ipywidgets import interact, widgets

"""## Plot A Function You Like

In this assignment, you have to design and plot one function your like.

There are three requirements:
1. Describe the function formulation explicity and the domain that you focus on. You can check the text cell below as a template. 
2. Complete the function ``plot_yours()`` defined below to plot the function defeind by you, note that you can find some elementary functions in Python using Numpy: https://numpy.org/doc/stable/reference/routines.math.html
3. Change some plot settings such as color of line, marker and linestyle. For more detail about plot settings, please check https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html
4. Plot the function in the prepared code cell, you will need to indicate values of endpoints ``a``, ``b,``, and the number ``n`` used to plot the function successfully. **A function graph is expected as an output.**
5. Plot your finction using interact() function. **A interact widget is expected as an output**

### 1. Describe your function and the domain you want to plot
The function I plot in this assignment is
$$
y = (\cos {x^2} + 1 )^x
$$
on $[2,5]$.
"""

# 2. Complete the function below to plot the function defined by you
def f(a, b, n):
    x = np.linspace(a, b, n)
    ### Define your own function here
    y = ( ( np.cos( x ** 2 ) + 1 ) ** x )
    ###
    plt.plot(x, y, "g:", lw=1)  
    ### 3. Change some plot settings
    plt.title("Oscillating function!")
    plt.legend(["$y = (\cos {x^2} + 1 )^x$"])
    ### y = ( cos x² + 1 )ˣ
    ###

# 4. Plot your function with specific
f(2,5,100)

# 5. Plot your function with interact() function

# Using trick from https://stackoverflow.com/questions/48316044/setting-default-values-in-sliders-using-interact
# Import widgets in order to control default value of n and steps.

def slider(mi, ma, sp, vl):
  widgets.IntSlider( min = mi, max = ma, step = sp, value = vl )

interact(f, a = widgets.IntSlider(min=-10,max=9,step=1,value=2), b = widgets.IntSlider(min=-9,max=10,step=1,value=5), n = widgets.IntSlider(min=2,max=200,step=1,value=50) )

"""# (Bonus) Design your own Python exercise 

In this part, you have a chance to be a Pyton instructor. You may each additional 1 point in this assignment with your creativity.

Based on recent course materials, please propose a Python exercise for other classmates. 

Note that you don't need to answer what you propose here. However, you need to describe your exercise as much detail as you can. 
"""

