# -*- coding: utf-8 -*-
"""Assignment01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/[REDACTED]

1. This Colab is designed for the course "[REDACTED]" instructed by [REDACTED].

2. First, copy this Colab notebook to your Drive. Then, read the instruction of this assignment. 

3. Rename copied notebbok to **[REDACTED]**. For example, **[REDACTED]**

4. When you complete your assignment, you need to:

  a. First, download your Colab notebook as a IPYNB file

  b. Next, upload downloaded Colab notebook to the specific drive folder [REDACTED] before **[REDACTED]**

  c. Then, please submit the link of your **uploaded** file to [REDACTED]. 
  
  The link of **uploaded** IPYNB file can be found by clicking **Share>Get Link** on the top right.
  
Note that you can re-submit your assigment by replacing the old one.

## Personal Information




Please fill in your details below.

Name: <font color="#666">[REDACTED]</font>

Student ID: <font color="#666">[REDACTED]</font>

Department/Program: <font color="#666">[REDACTED]</font>

## Python in your Imagination

本作業的目的旨在讓同學練習思考，何謂程式語言以及程式語言能協助你或其他人完成什麼樣的事情。無論同學是否了解Python或是程式語言，請依照同學目前所擁有的知識來回答下面三個問題：

The purpose of this assignment is to help you to think how Python could assist you and your collaborators. No matter you understand Python or not, please answer the following THREE questions based on current knowledge

<font color='red'>1. Daily life applications of Python</font>

請提出一個使用Python程式語言能達成的生活中的應用，並解釋Python是如何能幫助你達成目的。

Find one application of Python in your daily life and explain how Python works in this task.

<font color='blue'>Answer 1</font>

I would like to make a program showing all courses teaching at the moment on a NTU map. This will benefit students who want to find a class to sit in when they have spare time. <font color="#CCC"><s>And isn't that pretty cool to see all courses teaching at the same time?</s></font>

The expected user interface of the program might look like this:

---

&nbsp;&nbsp;<font size="6">NTU Course Map</font>&nbsp;&nbsp;Find all courses teaching at the moment.

&nbsp;&nbsp;Current Time: <font color="#864">2022-10-03 (MON) | 08:32 (UTC+8)</font> ⟳

&nbsp;&nbsp;Class Number: <font color="#864">1 (08:10～09:00)</font>

&nbsp;&nbsp;<font size="1">Click the course title for more information. Course titles in <font color="#906">red</font> are only taught on odd weeks, and those in <font color="#0A8">green</font> are only taught on even weeks.</font>

<table>
<thead>
  <tr>
    <th colspan="6">普通教學館 Putong Lecture Building</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td align="center">101</td>
    <td align="center">102</td>
    <td align="center">103</td>
    <td align="center"></td>
    <td align="center"></td>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center"></td>
    <td align="center"></td>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center">201</td>
    <td align="center">202</td>
    <td align="center">203</td>
    <td align="center">204</td>
    <td align="center">205</td>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2080130&class=06&dpt_code=0000&ser_no=01048&semester=111-1&lang=CH"><font color="#235">College Chinese:<br>Reading and Writing (I)</font></a><br>劉建志</td></td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center"></td>
  </tr>
  <tr>
    <td align="center">301</td>
    <td align="center">302</td>
    <td align="center">303</td>
    <td align="center">304</td>
    <td align="center">305</td>
    <td align="center">306</td>
  </tr>
  <tr>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=146%20U9080&class=05&dpt_code=1460&ser_no=69092&semester=111-1&lang=CH"><font color="#235">General Chinese<br>Language Course (I)</font></a><br>王曉君</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=146%20U9080&class=07&dpt_code=1460&ser_no=40740&semester=111-1&lang=CH"><font color="#235">General Chinese<br>Language Course (I)</font></a><br>劉孝生</td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2081121&class=02&dpt_code=0000&ser_no=01067&semester=111-1&lang=CH"><font color="#906">College Chinese:<br>Middle Level(1)</font></a><br>林貝珊</td>
  </tr>
  <tr>
    <td align="center">401</td>
    <td align="center">402</td>
    <td align="center">403</td>
    <td align="center">404</td>
    <td align="center">405</td>
    <td align="center">406</td>
  </tr>
  <tr>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2080120&class=07&dpt_code=0000&ser_no=01034&semester=111-1&lang=CH"><font color="#235">College Chinese:<br>Culture, Thought,<br>and Writing (I)<br></font></a>梁偉賢</td>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=146%20U9080&class=06&dpt_code=1460&ser_no=83825&semester=111-1&lang=CH"><font color="#235">General Chinese<br>Language Course (I)</font></a><br>蔡孟芳</td>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2080120&class=14&dpt_code=0000&ser_no=01035&semester=111-1&lang=CH"><font color="#235">College Chinese:<br>Culture, Thought,<br>and Writing (I)<br></font></a>侯傑之<br></td>
  </tr>
  <tr>
    <td align="center">501</td>
    <td align="center">502</td>
    <td align="center">503</td>
    <td align="center">504</td>
    <td align="center">505</td>
    <td align="center">506</td>
  </tr>
  <tr>
    <td align="center">---</td>
    <td align="center"><a href="http://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2080130&class=05&dpt_code=0000&ser_no=01047&semester=111-1&lang=CH"><font color="#235">College Chinese:<br>Reading and Writing (I)</font></a><br>李馥名</td>
    <td align="center"><a href="https://nol.ntu.edu.tw/nol/coursesearch/print_table.php?course_id=101%2081111&class=04&dpt_code=0000&ser_no=01063&semester=111-1&lang=CH"><font color="#235">College Chinese:<br>Advanced Language (1)</font></a><br>許育嘉</td>
    <td align="center">---</td>
    <td align="center">---</td>
    <td align="center">---</td>
  </tr>
</tbody>
</table>

---

<font color='red'>2. Major-based Application</font>

請提出一個你（認為）在兩月內可以完成，且與你主修專業相關的應用，並試著提出你在這兩個月的開發流程。

Based on your major, propose a Python application that can be implemented by yourself in two months. And, explain how to manage your development process.

<font color='blue'>Answer 2</font>

Sometimes I need to use [batch address to coordinate service](https://www.tgos.tw/tgos/Web/Address/TGOS_Address.aspx) provided by TGOS, MoI (Taiwan Geospatial One Stop, Ministry of Interior), but since they only provide 10,000 daily quota to convert and I have about 64,000 adresses, it will take too much time for me to use a week to convert them. I planned to make an application to do following things:

1. The application open the browser and go to [TGOS website](https://www.tgos.tw/tgos/Web/Address/TGOS_Address.aspx).

2. The application type in the address in the [file 1](https://raw.githubusercontent.com/imdataman/taipei-house-age-map/master/台北市建築使用執照.csv) and [file 2](https://gist.github.com/taipeinative/73e48d0d7befc334c68bed79ba7c0df9).

3. The application grab the coordinate returned from website and record them somewhere.

4. The application make the new .csv file ready for use with (1) original addresses (2) converted coordinates' longitude (3) converted coordinates' latitude.


After a short research, I found that in order to fulfill the quest, I need following tools:

1. Basic Python knowledge.

2. Beautiful Soup / Selenium / Any other web crawler package.

3. ...Any other unexpected tool.

The development progress might look like:

1. Add a read-csv-files feature.

2. Add a web crawler.

3. Make the web crawler able to grab the coordinates from TGOS.

4. Add a download-file-when-finished feature.

5. (If possible) Make a proper GUI.

<font color='red'>3. Research-based Application</font>

假使你有機會與自己系上的教授合作，你認為Python可以提供該教授在研究上什麼樣的協助呢？請簡述可能的研究計劃以及您在這個計畫中所扮演的角色。

Assume that you have a chance to cooperate with one professor in your department/program, what you could offer to assist this professor about their research? Please propose a possible research plan and explain your role in this project.

<font color='blue'>Answer 3</font>

If I have an opportunity to collaborate with a professor in my department, I may participate in projects where heavy calculations are needed. For example, I can code a program which can build or test the model of the relationship between temples and churches. The program should be able to calculate the correlation coefficients according to the equation and data provided by users or previous calculation results.
"""
